### ISSUE TITLE
Correction of the right turn gesture

### ISSUE THREAD

**Issue by EduardoColon** [WebCrest-Labs/livelyness_detection#8]
Hello, to fix the bug in the right turn gesture, you need to change the greater than sign to the less than sign in the file m7_livelyness_detection_screen.v2.dart:

`        if ((face.headEulerAngleY ?? 0) < (headTurnThreshold)) {
`

**Comment by GhagSagar23** [comment]
The updated version is rolled-out @EduardoColon. Please check and let me know.

**Comment by EduardoColon** [comment]
Ready @GhagSagar23 , it's working now! A question on another topic: what anti-spoofing measures does this project implement?
